/****************************************************************************
* LostPeterEngine - Copyright (C) 2022 by LostPeter
* 
* Author:   LostPeter
* Time:     2022-10-30
* Github:   https://github.com/LostPeter/LostPeterVulkan
* Document: https://www.zhihu.com/people/lostpeter/posts
*
* This code is licensed under the MIT license (MIT) (http://opensource.org/licenses/MIT)
****************************************************************************/

#ifndef _PRE_INCLUDE_H_
#define _PRE_INCLUDE_H_

#include "FPreInclude.h"

#include "PreDefine.h"
#include "EngineDefine.h"

#include "App.h"
#include "Sample.h"
#include "WindowBase.h"
#include "WindowListener.h"
#include "Window.h"

#include "Base.h"
#include "DataIndex.h"
#include "DataVertex.h"
#include "DataVertexIndex.h"
#include "Engine.h"
#include "EngineConfig.h"
#include "EngineFrameProfiler.h"
#include "EngineFrameState.h"
#include "EngineFrameStateAudio.h"
#include "EngineFrameStateMemory.h"
#include "EngineFrameStatePhysics.h"
#include "EngineFrameStateRender.h"
#include "EngineListener.h"
#include "Image.h"
#include "ImageCodec.h"
#include "ImageCodecDXT.h"
#include "ImageResampler.h"
#include "Material.h"
#include "MaterialData.h"
#include "MaterialDataManager.h"
#include "MaterialDataSerializer.h"
#include "MaterialInstance.h"
#include "MaterialManager.h"
#include "MaterialSerializer.h"
#include "Mesh.h"
#include "MeshDataSerializer.h"
#include "MeshManager.h"
#include "MeshSerializer.h"
#include "MeshSub.h"
#include "Movable.h"
#include "MovableListener.h"
#include "MovableFactory.h"
#include "Node.h"
#include "NodeListener.h"
#include "ObjectVisibleBoundsInfo.h"
#include "Object.h"
#include "ObjectMesh.h"
#include "ObjectSkinMesh.h"
#include "ObjectCameraListener.h"
#include "ObjectCamera.h"
#include "ObjectLight.h"
#include "ObjectTerrain.h"
#include "ObjectWater.h"
#include "ObjectSky.h"
#include "ObjectCloud.h"
#include "ObjectParticle.h"
#include "ObjectManager.h"
#include "Renderable.h"
#include "RenderableIndirect.h"
#include "RenderCapabilities.h"
#include "RenderEngineListener.h"
#include "RenderEngine.h"
#include "RendererListener.h"
#include "Renderer.h"
#include "RenderFrameBufferDescriptor.h"
#include "RenderPassDescriptor.h"
#include "RenderPassDescriptorManager.h"
#include "RenderPass.h"
#include "RenderPassListener.h"
#include "RenderPassQueue.h"
#include "RenderPassQuad.h"
#include "RenderPassSimple.h"
#include "RenderPassReflection.h"
#include "RenderPassRefraction.h"
#include "RenderPassDepthOnly.h"
#include "RenderPassGBuffer.h"
#include "RenderPassShadowCaster.h"
#include "RenderPassForwardLit.h"
#include "RenderPassDeferredLit.h"
#include "RenderPassSky.h"
#include "RenderPassSkinMesh.h"
#include "RenderPassMesh.h"
#include "RenderPassGrass.h"
#include "RenderPassTree.h"
#include "RenderPassTerrain.h"
#include "RenderPassWater.h"
#include "RenderPassOcean.h"
#include "RenderPassBillboard.h"
#include "RenderPassParticle.h"
#include "RenderPassLensFlare.h"
#include "RenderPassVolumeFog.h"
#include "RenderPassCameraFog.h"
#include "RenderPassPostProcess.h"
#include "RenderPassUI3D.h"
#include "RenderPassUI.h"
#include "RenderPassBackBuffer.h"
#include "RenderPassManager.h"
#include "RenderPipeline.h"
#include "RenderPipelineForward.h"
#include "RenderPipelineManager.h"
#include "RenderQueue.h"
#include "RenderQueueManager.h"
#include "RenderState.h"
#include "RenderTargetListener.h"
#include "RenderTarget.h"
#include "RenderTexture.h"
#include "RenderTargetManager.h"
#include "RenderWindowListener.h"
#include "RenderWindow.h"
#include "ResourceManualLoader.h"
#include "ResourceListener.h"
#include "Resource.h"
#include "ResourceManager.h"
#include "ResourceLoadingListener.h"
#include "ResourceGroupListener.h"
#include "ResourceGroupManager.h"
#include "SceneConfig.h"
#include "Scene.h"
#include "SceneData.h"
#include "SceneDataManager.h"
#include "SceneDataSerializer.h"
#include "SceneManager.h"
#include "SceneManagerEnumerator.h"
#include "SceneNode.h"
#include "SceneSerializer.h"
#include "ShaderParameter.h"
#include "ShaderParamPass.h"
#include "ShaderParamPassMain.h"
#include "ShaderParamPassDepth.h"
#include "ShaderParamPassCustom.h"
#include "ShaderParamPassManager.h"
#include "ShaderParamSourceAuto.h"
#include "ShaderProgram.h"
#include "ShaderProgramFactory.h"
#include "ShaderProgramManager.h"
#include "ShaderProgramGroup.h"
#include "ShaderProgramGroupManager.h"
#include "ShaderProgramSerializer.h"
#include "Shader.h"
#include "ShaderManager.h"
#include "Stream.h"
#include "StreamIndex.h"
#include "StreamIndexSystem.h"
#include "StreamLock.h"
#include "StreamManager.h"
#include "StreamTemp.h"
#include "StreamTempBlended.h"
#include "StreamTexture.h"
#include "StreamVertex.h"
#include "StreamVertexBinding.h"
#include "StreamVertexBindingManager.h"
#include "StreamVertexSystem.h"
#include "StreamUniform.h"
#include "StreamUniformSystem.h"
#include "SystemCapabilities.h"
#include "Texture.h"
#include "TextureManager.h"
#include "TextureSerializer.h"
#include "VertexDeclaration.h"
#include "VertexDeclarationManager.h"
#include "VertexElement.h"
#include "Viewport.h"


namespace LostPeterEngine
{	

}; //LostPeterEngine

#endif